### ISSUE TITLE
ログイン機能

### ISSUE THREAD

**Issue by yukiMizo** [AsahigaokaProhen/kokosai-app-75#18]
ログイン機能の作成

**Comment by pe-tanman** [comment]
混雑機能のために101-210, 309の店側権限も作って欲しいです

**Comment by yukiMizo** [comment]
ログイン機能作りました。
今年も去年と同じく個人でログインするシステムにしました。
まだ認証IDを全校生徒分作ったりしないといけないです...。
ログイン機能関連で何か質問があれば、聞いてください。
